# Generated by Django 3.0.5 on 2020-04-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pizza_name',
            new_name='pizza_fk',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='pizza_name',
            new_name='pizza_fk',
        ),
    ]
